#------------------------
# This file contains fallback configuration overwrites in case the agent is started with an invalid configuration
# In this case, the agent tries to preserve the inspecit.config settings and to attach them to the fallback configuration
# to make sure that runtime configuration updated are possible without a restart
#------------------------
inspectit:
  instrumentation:
    # settings for special sensors
    special:
      executor-context-propagation: false
      scheduled-executor-context-propagation: false
      thread-start-context-propagation: false
      http-url-connection-context-propagation: false
      apache-http-client-context-propagation: false
      servlet-api-context-propagation: false
      class-loader-delegation: false
  metrics:
    enabled: false
  tracing:
    enabled: false

  self-monitoring:
    enabled: false